# Generated by Django 4.2.3 on 2023-07-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('education', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('owner', 'Owner'), ('Admin1', 'Admin1'), ('secretary', 'Secretary')])),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('location', models.CharField(choices=[('Physically', 'Physically'), ('Online', 'Online')])),
                ('duration', models.CharField(max_length=200)),
                ('courseProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imath_Backend.addprovider')),
            ],
        ),
    ]
