# Generated by Django 4.2.3 on 2023-07-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imath_Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCourse',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='AddProvider',
            new_name='Provider',
        ),
    ]
